server:
  port: 8083 # todo-service 포트, (auth 8081, user 8082 등 나눌 예정)

spring:
  application:
    name: todo-service

  datasource:
    url: jdbc:postgresql://auth-db.cxauk2qcmmjm.ap-northeast-2.rds.amazonaws.com:5432/kingkitdb
    username: kingkit
    password: kingkitpass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: todo

  flyway:
    enabled: true
    schemas: todo
    locations: classpath:db/migration
