server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://auth-db.cxauk2qcmmjm.ap-northeast-2.rds.amazonaws.com:5432/authdb
    username: postgres
    password: 244589zz!!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
