server:
  port: 8082

spring:
  application:
    name: auth-service

jwt:
  secret: wjIxQcvXM5ZgWSnCWMxe0Loav5Wts63Hp/f01uWsj0Ixl4mG7qecuRkNEVxuVyOa84DItUhn1uXhP3NJn9mU8A==  # 32바이트 이상 Base64 인코딩
  access-token-validity: 3600000          # 1h  = 3 600 000 ms
  refresh-token-validity: 604800000       # 7d ≈ 604 800 000 ms

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

user-service:
  url: http://localhost:8081  # 예시: FeignClient base URL
