name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, user-service, billing-service, gateway]
    env:
      AWS_REGION: ap-northeast-2
      ECR_REPOSITORY: ${{ matrix.service }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build service JAR
        run: ./gradlew :core:${{ matrix.service }}:bootJar

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} ./core/${{ matrix.service }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.sha }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy $ECR_REPOSITORY" \
            --parameters commands="cd /home/ec2-user && ./deploy_ec2.sh $ECR_REPOSITORY ${{ github.sha }}" \
            --output text
        working-directory: deployment/scripts

