name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: auth-service
            module: core/auth-service
            build_task: :core:auth-service:bootJar
          - service: user-service
            module: core/user-service
            build_task: :core:user-service:bootJar
          - service: billing-service
            module: core/billing-service
            build_task: :core:billing-service:bootJar
          - service: gateway
            module: gateway
            build_task: :gateway:bootJar
    env:
      AWS_REGION: ap-northeast-2
      ECR_REPOSITORY: ${{ matrix.service }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build service JAR
        run: ./gradlew ${{ matrix.build_task }}

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} ./${{ matrix.module }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${{ github.sha }}

      - name: Upload deploy script
        run: |
          BASE64_SCRIPT=$(base64 -w0 deployment/scripts/deploy_ec2.sh)
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Upload deploy script" \
            --parameters commands="bash -c 'echo $BASE64_SCRIPT | base64 -d > /home/ec2-user/deploy_ec2.sh && chmod +x /home/ec2-user/deploy_ec2.sh'" \
            --output text

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy $ECR_REPOSITORY" \
            --parameters commands="cd /home/ec2-user && ./deploy_ec2.sh $ECR_REPOSITORY ${{ github.sha }}" \
            --output text
        working-directory: deployment/scripts

